Twitter
lkurash/Twitter pull request #1
Opened 2023-05-16 14:21 UTC by lkurash

2023-05-16 15:55 UTC, yukas requested changes

2023-05-16 15:55 UTC, yukas commented on server/error/ApiError.js
> +class ApiError extends Error{
```suggestion
class ApiError extends Error {
```

2023-05-16 15:55 UTC, yukas commented on client/public/index.html
> +<!DOCTYPE html>
Remove this file

2023-05-16 15:55 UTC, yukas commented on client/src/AppRouter.js
> +    <div>
Do we need this div?

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +  const listDays = (day) => {
Think of a more compact version of this function

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +  const listYears = (year) => {
Also more compact version here

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +          {
Remove the {

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +        <option disabled value={0} />
What is this for?

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +        {userSelectMonth === "February" &&
```js
{isFebruary() && listFebruaryDays.map(day => generateDayMarkup(day))}
{is30DaysMonth() && list30Days.map(...)}
{is31DaysMonth() && list31Days.map(...)}
```

2023-05-16 15:55 UTC, yukas commented on client/src/components/BirthForm.js
> +      {location === SIGNUP_PAGE ? (
Registration = RegistrationBirthFrom = BirthFrom + his button
ProfileEdit = ProfileEditBirthFrom = BirthFrom + his button

Registration = BirthFrom + his button
ProfileEdit = BirthFrom + his button

2023-05-17 16:46 UTC, yukas commented on client/src/components/BirthForm.js
> +  const optionDays = [];
dayOptions

2023-06-06 16:19 UTC, yukas commented on client/src/components/BirthForm.js
> +  const getDays = (countDay) => {
https://stackoverflow.com/questions/3746725/how-to-create-an-array-containing-1-n

2023-06-06 16:19 UTC, yukas commented on server/README.md
> +# Create Database
# Twitter

## Database setup

This project was made with PostgreSQL (https://www.postgresql.org/) and Sequelize (https://sequelize.org/).

### Install npm packages

`npm install`

### Create database config

`cd server`
`cp config/config.example.json config/config.json`

### Create database

`npx sequelize-cli db:create`

### Run migrations

`npx sequelize-cli db:migrate`

### Run seeds

`npx sequelize-cli db:seed:all`

or

`npx sequelize-cli db:seed --seed my-seed`

## Run the app

`npm run dev`

Open [http://localhost:5500](http://localhost:5500) to view it in your browser.

2023-06-23 04:33 UTC, Steve07101 approved these changes

2023-07-07 13:12 UTC, yukas commented on server/README.md
> +
Make `cd server` a first step

2023-07-07 13:12 UTC, yukas commented on server/README.md
> +### `npx sequelize-cli db:seed --seed my-seed`
`npx sequelize-cli db:seed --seed SEED_NAME`

2023-07-07 13:12 UTC, yukas commented on client/README.md
> +
You forgot `npm install`

2023-07-11 20:42 UTC, yukas requested changes

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const authorization = async (email, password) => {
Methods named using verbs, not nouns

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const authorization = async (email, password) => {
This is authentication, not an authorization

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const getUserInfo = async (email) => {
"Info" is an empty word. Don't use empty words such as "info", "data", etc.

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const users = await $host.get("api/user/allUsers");
"api/users"
"api/user/1"

Look at REST notation.

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const userProfile = await $authHost.post("api/user/profile", user);
"api/user"

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const following = await $authHost.post("api/user/following", {
POST: "api/user/{id}/follow" — Look at REST.

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const createFollow = async (followUserId) => {
`createFollower`

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const deleteFollow = async (followUserId) => {
`deleteFollower`

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const unFollow = await $authHost.post("api/user/deleteFollowing", {
Rule: variables are named with nouns: `response`

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const getFollowersUser = async (id) => {
`getFollowerUsers`

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +export const getFollowingUser = async (id) => {
`getFollowingUsers`

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const unFollow = await $authHost.post("api/user/deleteFollowing", {
Make url use the REST notation

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const allFollowing = await $authHost.get(`api/user/following/${id}`);
Make url use the REST notation

2023-07-11 20:42 UTC, yukas commented on client/src/http/userApi.js
> +  const allFollowers = await $authHost.get(`api/user/followers/${id}`);
Make url use the REST notation

2023-08-02 14:34 UTC, yukas commented on client/src/router.js
> +export const authRoutes = {
`authenticatedRoutes` or `privateRoutes`

2023-08-02 14:43 UTC, yukas commented on client/src/router.js
> +  element: <WrapperTwitterPage />,
This component should be named `Layout` or `AppLayout` etc

2023-08-02 14:45 UTC, yukas commented on client/src/router.js
> +  loader: authorization,
Better name would be `authenticate`

2023-08-02 14:46 UTC, yukas commented on client/src/router.js
> +  path: HOME_PAGE,
`HOME_PAGE_PATH`

2023-08-02 14:58 UTC, yukas commented on client/src/utils/constans.js
> +export const BOOKMARKS_PAGE = "/auth/bookmarks/";
Remove trailing slashes if it is unneded.

2023-08-02 15:02 UTC, yukas commented on client/src/router.js
> +  path: TWITTER_PAGE,
`ROOT_PAGE`

2023-08-02 15:02 UTC, yukas commented on client/src/router.js
> +  element: <WrapperTwitterPage />,
`PublicLayout`

2023-08-02 15:03 UTC, yukas commented on client/src/router.js
> +      element: <TwitterPage />,
`PublicHomePage`

2023-08-02 15:06 UTC, yukas commented on client/src/router.js
> +    },
Login and signup should be inside public routes, no need for a separate grouping

2023-08-02 15:31 UTC, yukas commented on client/src/components/forms/LoginForm.js
> +  const [showFormEmail, setShowFormEmail] = useState(true);
```suggestion
  const [passwordFieldVisible, setPasswordFieldVisible] = useState(false);
  const [emailFieldVisible, setemailFieldVisible] = useState(true);
```

2023-08-02 15:32 UTC, yukas commented on client/src/components/forms/LoginForm.js
> +  const showPasswordForm = () => {
```suggestion
  const showPasswordField = () => {
```

2023-08-02 15:43 UTC, yukas commented on client/src/components/forms/LoginForm.js
> +        usersStore.setAuth(true);
Try to follow the "Single level of abstraction rule" here:

```suggestion
        const authenticationResult = await authClient.authenticate(email, password);

        usersStore.setUserAuth(authenticationResult.user);
        localAuthClient.setAuthToken(authenticationResult.token);
        
```

2023-08-02 15:45 UTC, yukas commented on client/src/components/forms/LoginForm.js
> +        signInKeyDown={signInKeyDown}
This seems should be inside the component itself.

2023-08-02 15:56 UTC, yukas commented on client/src/components/forms/LoginForm.js
> +    // <div className="body">
```suggestion
      if (showPasswordForm) {
        <LoginEmailForm
          email={email}
          setEmail={setEmail}
          showFormEmail={showFormEmail}
          setShowFormEmail={setShowFormEmail}
        />
      } else {
        <LoginPasswordForm
```

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +import AppLayout from "./pages/AppLayout";
Imports structure:
```
// utils
// public
// private
// components

or
// utils
// pages
// components
```

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      path: "",
`EXPLORE_PATH_ROOT` or some other constant, but not the string itself

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      path: `${TRENDS_PAGE_PATH}:trend`,
Add `:trend` part into the constant

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +  path: "/authentication",
`auth` is a better name here

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      path: "/authentication/redirect",
`auth/login/redirect`

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      path: "",
Use constant here

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      path: `${AUTHEXPLORE_PAGE_PATH}`,
No need for string interpolation here

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +      // element: <UserPageComponent />,
Don't comment out things, use git to save things for future if needed.

2023-08-22 15:51 UTC, yukas commented on client/src/router.js
> +          element: [<UserTwits key={'twits'}/>, <EditProfilePageComponent key={'form'}/>],
Create a separate component for this

2023-08-26 13:18 UTC, yukas commented on client/src/utils/constans.js
> +export const PUBLIC_USERS_PAGE_PATH = "/profile/";
Use `/user/` instead of `/profile/`

2023-08-26 13:18 UTC, yukas commented on client/src/utils/constans.js
> +export const PRIVATE_USER_PAGE_PATH = "/:id";
The "private" prefix seems pretty useless here, try to remove it

2023-08-26 13:21 UTC, yukas commented on client/src/utils/constans.js
> +
Add a comment to the each group

2023-08-26 13:23 UTC, yukas commented on client/src/router.js
> +export const authorizationRoutes = {
`authorizationRoutes`

2023-08-26 13:29 UTC, yukas commented on client/src/http/index.js
> +import axios from "axios";
Rename this file to outline what really done in it

2023-08-26 13:35 UTC, yukas commented on client/src/http/index.js
> +  baseURL: "http://localhost:5500",
Move it to the constant

2023-08-26 13:36 UTC, yukas commented on client/src/http/userApi.js
> +class UserApi {
The class should be named `UserClient`

2023-08-26 13:38 UTC, yukas commented on client/src/http/twitsApi.js
> +class TwitsApi {
`TwitsClient`

2023-08-26 13:38 UTC, yukas commented on client/src/http/trendsApi.js
> +class Trends {
`TrendsClient`

2023-08-26 13:39 UTC, yukas commented on client/src/http/trendsApi.js
> +const trendsApi = new Trends();
`const trendsClient = ...`

2023-08-26 13:39 UTC, yukas commented on client/src/http/trendsApi.js
> +      `api/twitter//trends/trend/${trendId}/user/${userId}`
Remove unneded slash

2023-09-11 16:20 UTC, merged